files: \.(py)$
default_stages: [pre-commit, manual]
repos:

-   repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.11.12
    hooks:
    - id: ruff
      args: [
      --fix, --unsafe-fixes, --exit-non-zero-on-fix,
      --target-version, "py313", --select, "ALL",
      --ignore, "DOC,D,E501,S101,T201,CPY001,INP001",
      ]
    - id: ruff-format

-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.16.0
    hooks:
    - id: mypy
      additional_dependencies: [types-beautifulsoup4,types-requests]
      stages: [manual]

-   repo: https://github.com/dosisod/refurb
    rev: v2.1.0
    hooks:
    - id: refurb
      args: [--python-version, "3.12"]
      stages: [manual]
